/**
 * Safety Enforcer Agent (SafetyEnforcerAgent)
 * Part of the AgriSustain ADK Multi-Agent Team.
 * 
 * Mandate: Audit all recommendations generated by specialist agents. If a chemical
 * substance is suggested, query the MCP Policy Validation tool. If the policy flags an
 * ecological or dosage violation, block it and replace it with a safe organic/biological option.
 */

export interface SafetyAuditInput {
  zoneId: string;
  proposedSubstance?: string;
  proposedDosage?: number;
  specialistRecommendation: string;
}

export interface SafetyAuditResult {
  agentName: "SafetyEnforcerAgent";
  isApproved: boolean;
  securityCheckCode: string;
  auditDetails: string;
  finalRecommendation: string;
  substanceApplied?: string;
  dosageApplied?: number;
}

export class SafetyEnforcerAgent {
  private name = "SafetyEnforcerAgent";
  private systemPrompt = `You are a Safety Auditor and Environmental Compliance Officer.
Your primary role is to verify crop treatment recommendations against environmental policies.
You check for pesticide bans, pesticide-water-source proximity limits, and maximum dosage limits.
If a recommendation violates policies, you MUST override it with an eco-safe alternative.`;

  // Safe Organic Fallback Alternatives mapping
  private organicFallbacks: Record<string, { substance: string; dosage: number; guide: string }> = {
    "copper_sulfate": {
      substance: "baking_soda_solution",
      dosage: 5.0,
      guide: "BLOCKED: Copper Sulfate treatment violated safety buffers. Replaced with safe baking soda solution spray (5g/sqm) combined with horticultural oil."
    },
    "sulfur": {
      substance: "neem_oil",
      dosage: 10.0,
      guide: "BLOCKED: Sulfur application restricted for this crop. Replaced with organic Neem Oil spray (10g/sqm) and compost tea spray."
    },
    "paraquat": {
      substance: "mechanical_weeding",
      dosage: 0,
      guide: "BLOCKED: Globally banned herbicide Paraquat proposed. Replaced with recommendation for mechanical weeding and straw mulching."
    }
  };

  /**
   * Performs audit by querying the safety evaluator.
   * In a live system, this calls the MCP tool `propose_treatment`
   */
  public audit(
    input: SafetyAuditInput,
    mcpValidateFn: (zoneId: string, substance: string, dosage: number) => { approved: boolean; code: string; reason?: string }
  ): SafetyAuditResult {
    const { zoneId, proposedSubstance, proposedDosage, specialistRecommendation } = input;

    if (!proposedSubstance || !proposedDosage) {
      // No chemicals proposed, passes audit automatically
      return {
        agentName: "SafetyEnforcerAgent",
        isApproved: true,
        securityCheckCode: "PASSED_NO_CHEMICALS",
        auditDetails: "Safety Audit Passed: No chemical substances recommended by specialists.",
        finalRecommendation: specialistRecommendation
      };
    }

    // Call MCP Validation (Safe Execution checkpoint)
    const mcpResponse = mcpValidateFn(zoneId, proposedSubstance, proposedDosage);

    if (mcpResponse.approved) {
      return {
        agentName: "SafetyEnforcerAgent",
        isApproved: true,
        securityCheckCode: mcpResponse.code,
        auditDetails: `Safety Audit Cleared: ${mcpResponse.reason}`,
        finalRecommendation: specialistRecommendation,
        substanceApplied: proposedSubstance,
        dosageApplied: proposedDosage
      };
    } else {
      // Security rule failed - trigger Safe Execution Fallback
      const substanceKey = proposedSubstance.toLowerCase();
      const fallback = this.organicFallbacks[substanceKey] || {
        substance: "compost_tea",
        dosage: 20,
        guide: `BLOCKED: Chemical application of '${proposedSubstance}' was flagged. Replaced with aerated organic compost tea spray.`
      };

      return {
        agentName: "SafetyEnforcerAgent",
        isApproved: false,
        securityCheckCode: mcpResponse.code,
        auditDetails: `SECURITY RULE BREACH: ${mcpResponse.reason} Triggering safe execution fallback.`,
        finalRecommendation: `${fallback.guide} (Original advice was: ${specialistRecommendation})`,
        substanceApplied: fallback.substance,
        dosageApplied: fallback.dosage
      };
    }
  }

  public getAgentMetadata() {
    return {
      name: this.name,
      prompt: this.systemPrompt,
      capabilities: ["compliance_audit", "remediation_fallback"]
    };
  }
}
